---
format: html
toc: true
title: "Interview duration stats"
embed-resources: true
execute: 
  echo: false
  error: false
  warning: false
---

```{r}
#| label: set table colors

bics_header_color <- "#006a4d"
bics_row_group_color <- "#6eb6a2"

style_table <- function(
  gt_tbl,
  header_color = bics_header_color,
  row_group_color = bics_row_group_color
) {

  tbl_styled <- gt_tbl |>
    gt::tab_options(
      heading.background.color = header_color,
      column_labels.background.color = header_color,
      row_group.background.color = row_group_color
    )

  return(tbl_styled)

}

```

## By each module, overall

```{r}
#| label: duration by module
duration_by_module <- readRDS(
  file = here::here("data", "04_created", "duration_by_module.rds")
)

duration_by_module |>
  gt::gt() |>
	gt::fmt_number(
    columns = c(med, sd, min, max),
    decimals = 2
  ) |>
  gt::opt_row_striping(row_striping = TRUE) |>
	gt::cols_width(section ~ gt::pct(50)) |>
	gt::opt_interactive(
    use_search = TRUE,
    page_size_default = 20,
    use_resizers = TRUE
  ) |>
	style_table()
```

## By non-individual module, overall

```{r}
#| label: duration by non-individual module

duration_by_non_indiv_module <- readRDS(
  file = here::here("data", "04_created", "duration_by_non_indiv_module.rds")
)

duration_by_non_indiv_module |>
	gt::gt() |>
	gt::fmt_number(
    columns = c(med, sd, min, max),
    decimals = 2
  ) |>
  gt::opt_row_striping(row_striping = TRUE) |>
	style_table()
```

## By individual module

### Overall

```{r}
#| label: overall duration by individual module

duration_by_module_indiv_overall <- readRDS(
  file = here::here("data", "04_created", "duration_by_module_indiv_overall.rds")
)

duration_by_module_indiv_overall |>
  gt::gt() |>
	gt::fmt_number(
    columns = c(med, sd, min, max),
    decimals = 2
  ) |>
  gt::opt_row_striping(row_striping = TRUE) |>
	style_table()

```

### Per person

```{r}
#| label: duration by module per person
duration_by_module_per_person <- readRDS(
  file = here::here("data", "04_created", "duration_by_module_per_person.rds")
)

duration_by_module_per_person |>
  gt::gt() |>
	gt::fmt_number(
    columns = c(med, sd, min, max),
    decimals = 2
  ) |>
  gt::opt_row_striping(row_striping = TRUE) |>
	style_table()
```

## By select questions

```{r}
#| label: duration for select questions

duration_by_questions_by_module <- readRDS(
  file = here::here("data", "04_created", "duration_by_questions_by_module.rds")
)

duration_by_questions_by_module |>
  gt::gt() |>
	gt::fmt_number(
    columns = c(med, sd, min, max),
    decimals = 2
  ) |>
  gt::opt_row_striping(row_striping = TRUE) |>
	style_table()
```
